[project]
name = "docling-serve-modal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling-serve[ui]>=1.7.0",
    "modal>=1.2.0",
]
